# -*- coding: utf-8 -*-
"""LBP_Yolov_82.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kPuy0rYoyjF4Dp4z8ldX1fP2vguumlti
"""

!pip install ultralytics
from ultralytics import YOLO
from google.colab import drive
import os
import numpy as np
import yaml
drive.mount('/content/drive')

print("Current Wdir: ", os.getcwd());
print("Query dir: ", os.listdir('../content/drive/MyDrive/Colab Notebooks/OsteoYOLO/datasets/LBP-ISBI_82'));



# Load a pretrained YOLO model (recommended for training)
model = YOLO('yolov8x-cls.pt')

# Train the model using the dataset for 3 epochs
results = model.train(data='../content/drive/MyDrive/Colab Notebooks/OsteoYOLO/datasets/LBP-ISBI_82', epochs=20, batch=10)

# Evaluate the model's performance on the validation set
results = model.val()

import numpy as np
path = '../content/drive/MyDrive/Colab Notebooks/OsteoYOLO/datasets/OsteoClassification/test/'
fnames = os.listdir(path + 'Normal');

for i in range(np.size(fnames)):
  print(fnames[i])
  model(path + 'Normal/' + fnames[i])

fnames = os.listdir(path + 'Osteo');

for i in range(np.size(fnames)):
  print(fnames[i])
  model(path + 'Osteo/' + fnames[i])